import {
  Home,
  ShoppingCart,
  Utensils,
  Car,
  Smartphone,
  Zap,
  HeartPulse,
  Shirt,
  Sofa,
  Baby,
  GraduationCap,
  Dog,
  Gamepad2,
  Plane,
  Users,
  Church,
  Wallet,
  Landmark,
  TrendingUp,
  Shield,
  Building2,
  Briefcase,
  CreditCard,
  Gift,
  Repeat,
  Banknote,
  CircleHelp,
  type LucideIcon,
} from 'lucide-react'

const ICONS: Record<string, LucideIcon> = {
  home: Home,
  'shopping-cart': ShoppingCart,
  utensils: Utensils,
  car: Car,
  smartphone: Smartphone,
  zap: Zap,
  'heart-pulse': HeartPulse,
  shirt: Shirt,
  sofa: Sofa,
  baby: Baby,
  'graduation-cap': GraduationCap,
  dog: Dog,
  'gamepad-2': Gamepad2,
  plane: Plane,
  users: Users,
  church: Church,
  wallet: Wallet,
  landmark: Landmark,
  'trending-up': TrendingUp,
  shield: Shield,
  'building-2': Building2,
  briefcase: Briefcase,
  'credit-card': CreditCard,
  gift: Gift,
  repeat: Repeat,
  banknote: Banknote,
  'circle-help': CircleHelp,
}

export function getCategoryIcon(icon: string | null | undefined): LucideIcon {
  return (icon && ICONS[icon]) || CircleHelp
}
